### ISSUE TITLE
DeAOT training & inference.

### ISSUE THREAD

**Issue by z-jiaming** [henghuiding/MOSE-api#10]
Since you uploaded the code of XMem, could you please also provide the train_datasets.py and eval_datasets.py of aot-benchmark for MOSE?
And did you change the training config, or same as YTB, like
`self.DATA_MOSE_REPEAT = 1, self.DATA_RANDOM_GAP_MOSE = 3`

Thanks a lot!

**Comment by henghuiding** [comment]
Hi Jiaming,

Thank you for your valuable suggestions and attention to MOSE! Done as suggested. 

We did not change the training config, same as defaulting setting of YTB.

**Comment by z-jiaming** [comment]
Thanks for you reply!
But there seems to be a problem with the two files in the deaot.

1) MOSE dose not have meta.json like YouTubeVOS?
https://github.com/henghuiding/MOSE-api/blob/bd13bafea70bc5702e45bf03d90cc0fe8d8eeffa/DeAOT_train_datasets.py#L601-L602

2) MOSE's file structure is split outside of A and B
https://github.com/henghuiding/MOSE-api/blob/bd13bafea70bc5702e45bf03d90cc0fe8d8eeffa/DeAOT_eval_datasets.py#L292-L293

It better should be:
`self.image_root = os.path.join(root, split, 'JPEGImages')`
`self.label_root = os.path.join(root, split, 'Annotations')`

**Comment by henghuiding** [comment]
Thank you for your careful check👍

1. Currently no, while we consider providing a meta.json soon, which plans to include more information. You could ignore [Line 602](https://github.com/henghuiding/MOSE-api/blob/bd13bafea70bc5702e45bf03d90cc0fe8d8eeffa/DeAOT_train_datasets.py#L602) or generate a meta.json by yourself, which does not affect the model training.

2. Yes you're right, updated accordingly. It depends on how you arrange the files. On my local machine it is  `JPEGImages/train`.

Thank you again for your suggestions and all the best to your work!

**Comment by z-jiaming** [comment]
If I just ignore Line 602, how should I filter out short objects like L612-L619?

**Comment by ntuLC** [comment]
Hi Jiaming,

> Thanks for you reply! But there seems to be a problem with the two files in the deaot.
> 
> 1. MOSE dose not have meta.json like YouTubeVOS?
>    https://github.com/henghuiding/MOSE-api/blob/bd13bafea70bc5702e45bf03d90cc0fe8d8eeffa/DeAOT_train_datasets.py#L601-L602
> 2. MOSE's file structure is split outside of Annotations and JPEGImages
>    https://github.com/henghuiding/MOSE-api/blob/bd13bafea70bc5702e45bf03d90cc0fe8d8eeffa/DeAOT_eval_datasets.py#L292-L293
> 
> It better should be: `self.image_root = os.path.join(root, split, 'JPEGImages')` `self.label_root = os.path.join(root, split, 'Annotations')`



We are glad to announce that we just updated meta files for the dataset. Please check them out! The current file structure is organized for better packaging&uploading. Feel free to reorganize the folder structures as you like after you download.



> If I just ignore Line 602, how should I filter out short objects like L612-L619?
> 
> In addition, should I filter out short videos?
> 
> Thanks again!


In terms of filtering out short videos as you've mentioned, there are no strict requirements. So you can decide whether to filter out videos based on the method you are using.

Enjoy!

**Comment by z-jiaming** [comment]
Thank you for your active response!
