### ISSUE TITLE
Validation split still only has 1 image per folder

### ISSUE THREAD

**Issue by joshmyersdean** [henghuiding/MOSE-api#17]
Hello!

Thank you for this work! I recently downloaded the validation split of MOSE from the given OneDrive link and it appears that all videos only have 1 annotation. I used the link provided in #8.

Thank you!

Related issues: #4

**Comment by Superviro** [comment]
Same problem here :(

**Comment by henghuiding** [comment]
Hi,

Thank you for your attention.

#4 is not the related issues.

The annotation masks of validation split are not released, please submit your validation predictions to [MOSE CodaLab Evaluation Server](https://codalab.lisn.upsaclay.fr/competitions/10703) to get your scores.

The released 1 annotation is used as reference for the semi-supervised VOS setting.
