### ISSUE TITLE
Annotation tool

### ISSUE THREAD

**Issue by quangtrungtruong** [henghuiding/MOSE-api#7]
Thank you for your wonderful work! Could you share the annotation tool used to build the dataset? I appreciate if you can release codes for annotation tool.

**Comment by henghuiding** [comment]
Thank you for your interest! We do not plan to release the annotation tool anytime soon. We recommend [XMem GUI](https://github.com/hkchengrex/XMem/blob/main/docs/DEMO.md), which is a strong annotation tool.
