### ISSUE TITLE
Why videos with only one frame?

### ISSUE THREAD

**Issue by fiskrt** [henghuiding/MOSE-api#8]
Hi, why are there "videos" in the dataset with only one frame?
For example `330ac20d, 9eb92f21, a4287634, ce1ea47c`.

I'm just curious if there's a reason, otherwise, thanks for this dataset.

**Comment by henghuiding** [comment]
>Hi,
>
>Thanks for your interest and feedback! We missed it during the data filtering, but this data won't affect the training of 
  existing methods. The validation and testing set does not contain such cases, so you can safely ignore it. We'll carefully 
  process all the training folders again and update a version later.
>
>_Originally posted by @ntuLC in https://github.com/henghuiding/MOSE-api/issues/4#issuecomment-1454787385_

Thanks for your interest and feedback! Please download the updated version from [***OneDrive*** ](https://entuedu-my.sharepoint.com/:f:/g/personal/liuc0058_e_ntu_edu_sg/EjXSfDF7QEZApAVpFJ5rfdABkHCf0k2Va6VDfUy7rpabNw?e=9BVkrz).
