### ISSUE TITLE
Training setting

### ISSUE THREAD

**Issue by z-jiaming** [henghuiding/MOSE-api#9]
Thanks for your work!

I want to ask about the training setting. Your paper said "We replace the training dataset of previous methods from YouTubeVOS with our MOSE and strictly follow their training settings on YouTube-VOS [3]."

Most previous works training on YouTube-VOS and DAVIS in the main-training after the image pre-training.
Do you remove the DAVIS dataset? If that's the case, is it because you tested that removing DAVIS worked better?

Thanks a lot for your answer!

**Comment by heshuting555** [comment]
Thank you for your interest!

We download checkpoint trained on stage 0 (static) and then conduct training on MOSE only to report result fairly for all the methods.

**Comment by z-jiaming** [comment]
Thanks for your reply!

**Comment by z-jiaming** [comment]
Could you please tell me the training setting of MOSE if not same as main-training(DAVIS+YouTube-VOS)?
Such as iterations in XMem method, or just same as s2_xxx/s3_xxx in XMem?

**Comment by heshuting555** [comment]
using the following command to train on MOSE only.

`python -m torch.distributed.launch --master_port 25763 --nproc_per_node=2 train.py --exp_id retrain_stage3_only --stage 3 --load_network saves/XMem-s0.pth
`

**Comment by z-jiaming** [comment]
Thanks a lot!
Congratulations for ICCV 2023~~
